### ISSUE TITLE
Cannot create configmaps based on tutorial commands

### ISSUE THREAD

**Issue by ed-spiredigital** [sethvargo/vault-kubernetes-workshop#13]
```
ed@cloudshell:~ (xxxxxxxxxx)$ kubectl create configmap vault \
>   --from-literal "load_balancer_address=$(vault-lb-ip)" \
>   --from-literal "gcs_bucket_name=${GOOGLE_CLOUD_PROJECT}-vault-storage" \
>   --from-literal "kms_project=${GOOGLE_CLOUD_PROJECT}" \
>   --from-literal "kms_region=us-east1" \
>   --from-literal "kms_key_ring=vault" \
>   --from-literal "kms_crypto_key=vault-init" \
>   --from-literal="kms_key_id=projects/$(google-project)/locations/$(google-region)/keyRings/vault/cryptoKeys/vault-init"
-bash: vault-lb-ip: command not found
-bash: google-project: command not found
-bash: google-region: command not found
configmap/vault created
```

This is in the google cloud shell using bash. It does not reference those values anywhere before this page and those values don't work on google cloud shell.

**Comment by kutay** [comment]
These values are defined in the [__helpers.sh](https://github.com/sethvargo/vault-kubernetes-workshop/blob/02744fd1a76710b86ee9e2e741cb9d4f46779dee/scripts/__helpers.sh) script.
This script is sourced in other scripts, that's why it works.

So, you can either clone the project in cloud shell and run the script, or define these values by using the functions listed in the __helpers.sh

**Comment by den-vasyliev** [comment]
use shell variables
and kms_region should be global

**Comment by sethvargo** [comment]
I think the confusion is around the fact that this is both a standalone project and a codelab on developers.google.com. I have updated the codelab to reflect the "us-east1" KMS region.
